import images from "./assets/getItems"
export const tourPackages = [
  {
    id: 1,
    image: images.HomeCardShahiZinda,
    titleKey: "detailedTours.1.title",
    durationTagKey: "detailedTours.1.durationTag",
    seasonTagKey: "detailedTours.1.seasonTag",
    days: 7,
    nights: 6,
    peopleKey: "detailedTours.1.people",
    seasonKey: "detailedTours.1.season",
    descriptionKey: "detailedTours.1.description",
    locationsKeys: [
      "detailedTours.1.locations.0",
      "detailedTours.1.locations.1",
      "detailedTours.1.locations.2",
    ],
    highlightsKeys: [
      "detailedTours.1.highlights.0",
      "detailedTours.1.highlights.1",
      "detailedTours.1.highlights.2",
      "detailedTours.1.highlights.3",
      "detailedTours.1.highlights.4",
    ],
  },
  {
    id: 2,
    image: images.HomeCardGoldenRing,
    titleKey: "detailedTours.2.title",
    durationTagKey: "detailedTours.2.durationTag",
    seasonTagKey: "detailedTours.2.seasonTag",
    days: 10,
    nights: 9,
    peopleKey: "detailedTours.2.people",
    seasonKey: "detailedTours.2.season",
    descriptionKey: "detailedTours.2.description",
    locationsKeys: [
      "detailedTours.2.locations.0",
      "detailedTours.2.locations.1",
      "detailedTours.2.locations.2",
      "detailedTours.2.locations.3",
    ],
    highlightsKeys: [
      "detailedTours.2.highlights.0",
      "detailedTours.2.highlights.1",
      "detailedTours.2.highlights.2",
      "detailedTours.2.highlights.3",
      "detailedTours.2.highlights.4",
    ],
  },
  {
    id: 3,
    image: images.FerganaTour, // qo‘shimcha rasm qo‘shaman xoxlasangiz
    titleKey: "detailedTours.3.title",
    durationTagKey: "detailedTours.3.durationTag",
    seasonTagKey: "detailedTours.3.seasonTag",
    days: 5,
    nights: 4,
    peopleKey: "detailedTours.3.people",
    seasonKey: "detailedTours.3.season",
    descriptionKey: "detailedTours.3.description",
    locationsKeys: [
      "detailedTours.3.locations.0",
      "detailedTours.3.locations.1",
      "detailedTours.3.locations.2",
    ],
    highlightsKeys: [
      "detailedTours.3.highlights.0",
      "detailedTours.3.highlights.1",
      "detailedTours.3.highlights.2",
    ],
  },
  {
    id: 4,
    image: images.AralTour,
    titleKey: "detailedTours.4.title",
    durationTagKey: "detailedTours.4.durationTag",
    seasonTagKey: "detailedTours.4.seasonTag",
    days: 4,
    nights: 3,
    peopleKey: "detailedTours.4.people",
    seasonKey: "detailedTours.4.season",
    descriptionKey: "detailedTours.4.description",
    locationsKeys: [
      "detailedTours.4.locations.0",
      "detailedTours.4.locations.1",
    ],
    highlightsKeys: [
      "detailedTours.4.highlights.0",
      "detailedTours.4.highlights.1",
      "detailedTours.4.highlights.2",
    ],
  },
  {
    id: 5,
    image: images.TermizTour,
    titleKey: "detailedTours.5.title",
    durationTagKey: "detailedTours.5.durationTag",
    seasonTagKey: "detailedTours.5.seasonTag",
    days: 3,
    nights: 2,
    peopleKey: "detailedTours.5.people",
    seasonKey: "detailedTours.5.season",
    descriptionKey: "detailedTours.5.description",
    locationsKeys: [
      "detailedTours.5.locations.0",
      "detailedTours.5.locations.1",
    ],
    highlightsKeys: [
      "detailedTours.5.highlights.0",
      "detailedTours.5.highlights.1",
    ],
  },
];